Repository JR-Abstract/reddit-clone-abstract, pull requests merged in 2024-03, with the labels that each got.

#57 Fix: Updated User model with timestamp and minor adjustments
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/User.java
Labels: bug

#59 19 implement mapper for post entity
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/controller/PostController.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/PostMapper.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/Post.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/PostService.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/UserService.java
  src/test/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/PostMapperTest.java
Labels: enhancement

#41 Added Maven-surefire-plugin to file pom.xml . Created file run_test.y…
  .github/workflows/run_tests.yml
  pom.xml
Labels: test

#82 Added: error entity
  .run/localhost.run.xml
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/ErrorEntity.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/FieldErrorEntity.java
Labels: code-quality

#103 Added: readme.md file and license
  LICENSE
  README.md
Labels: documentation

#88 Updated: change username to userId in subredditDto
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/dto/SubredditRequestDTO.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/SubredditMapper.java
  src/main/resources/application.properties
  src/test/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/SubredditMapperTest.java
Labels: enhancement, code-quality

#102 68 changing vote
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/controller/VoteController.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/dto/VoteDto.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/Vote.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/repository/VoteRepository.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/VoteService.java
  src/test/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/VoteServiceTest.java
Labels: enhancement

#95 66 implement authorities and 69
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/config/SecurityConfig.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/Role.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/User.java
  src/main/resources/ignore/postgres_DDL.sql
Labels: enhancement, security

#87 Added: Global exception handler and handle post exception
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/SimpleErrorEntity.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/GlobalApplicationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/PostCreationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/PostNotFoundException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/SimpleApplicationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/handler/GlobalExceptionHandler.java
Labels: code-quality

#85 Added: validation for post, exceptions, binding result service to handle, some refactor
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/controller/PostController.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/dto/PostRequestDto.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/dto/PostResponseDto.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/ErrorEntity.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/FieldErrorEntity.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/error/SimpleErrorEntity.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/GlobalApplicationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/PostCreationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/PostNotFoundException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/exception/SimpleApplicationException.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/PostMapper.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/repository/PostRepository.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/BindingResultService.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/PostService.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/validator/PostRequestValidator.java
  src/test/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/mapper/PostMapperTest.java
Labels: code-quality

#112 Added: pagination and sorting to posts
  .gitignore
  .run/localhost.run.xml
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/controller/PostController.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/Post.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/PostService.java
  src/main/resources/application.properties
  src/main/resources/ignore/postgres_DDL.sql
  src/test/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/PostServiceTest.java
Labels: enhancement

#109 16 17 mail service
  .run/localhost.run.xml
  localhost.env
  pom.xml
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/config/SecurityConfig.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/controller/ActivationController.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/ActivationToken.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/model/User.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/repository/ActivationTokenRepository.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/ActivationTokenService.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/AuthService.java
  src/main/java/ua/com/javarush/oleksandr/reddit/redditcloneabstract/service/MailService.java
  src/main/resources/application.properties
  src/main/resources/ignore/postgres_DDL.sql
Labels: enhancement
